### ISSUE TITLE
Plot forward selection with another evaluation metric

### ISSUE THREAD

**Issue by sandervh14** [PythonPredictions/cobra#110]
# Task Title

Task: Plot forward selection with another evaluation metric

## Task Description

Business user wants to see forward selection plot computed with the MAE evaluation metric.

**Comment by sborms** [comment]
You can close it if you deem the recent commits sufficient. :-)

**Comment by sandervh14** [comment]
OK, the submitted pull request indeed solves this good enough.
Selecting even other metrics (e.g. F1 for classification etc.) will be done later, is not on the critical roadmap for the current milestone, focusing on linear regression.
