### ISSUE TITLE
 Reorganise evaluation

### ISSUE THREAD

**Issue by MatthiasRoelsPython** [PythonPredictions/cobra#13]
In a previous phase, the model evaluation is decoupled from the model building phase. In the later, only __one metric__ was used for optimisation where in the former, many metrics can be used to evaluate the final model. After adding the options to use different algorithms (SVM, linear regression with continuous target, ...) for building your model, there should also be different options for evaluation as there are different types of models:

- Binary target with binary scoring: basic evaluator class for binary model (contains accuracy, F1, precision, recall, ...)
- Binary target with probabilistic scoring: basic evaluator (with threshold on probability) + AUC, lift, gains and lift curves, roc curve, ...) 
- Multi class model
- Ordinal regression models 
- continuous target
- ...

All of these types of models can have different `Evaluator` classes, so it is important to use inheritance as much as possible, as well as having the proper utility functions split off for plotting.

**Comment by sborms** [comment]
New version will have ClassificationEvaluator and RegressionEvaluator classes, with separate metrics and plotting. Inheritance would be overkill, but might be useful if we add more model types.
