### ISSUE TITLE
Automatically search for categorical variables

### ISSUE THREAD

**Issue by ZlaTanskY** [PythonPredictions/cobra#137]
This can be done automatically instead of having to calculate them again and again to send them as keywords.

**Comment by patrickleonardy** [comment]
@ZlaTanskY How exactly do you want to calculate that automatically? 

I thought about automatically assigning *String variables* and each variable that has less unique values than a certain threshold, but by doing this the user would afterwards always have to verify if those assumptions are correct considering the data at hand. 
Do you have an other idea in mind how this could be implemented ? 

Or did you mean to put the data in a *data object* that defines *continuous_vars*, *discrete_vars* and *target_column_name* once  as attributes and functions that use this object can just go and automatically look it up ?

**Comment by sandervh14** [comment]
Hey @patrickleonardy, I seem to remember discussing this earlier with Jano and think it was the first thing.

The approach is really the one you wrote, and actually we thought of just taking the code that we now often write in our tutorials, we just thought it to be stupid that each and everyone of us needs to repeat that code on every case when most of the time these data type assumptions end up correctly and no corrections are needed.

To be sure, you could make Cobra throw a warning like "Assumed continuous variable type for the variables [...]. Assumed categorical variable type for the variables [...]."

Regards and see you later!
