### ISSUE TITLE
NaN column not preprocessed properly

### ISSUE THREAD

**Issue by ZlaTanskY** [PythonPredictions/cobra#138]
`Missing values must be missing in the same location both left and right sides`

Dropping the column fixed the issue, but this should be possible to be dropped in backend or maybe raise a more descriptive exception which informs the user about the actual column for example.

**Comment by sandervh14** [comment]
Assigned this to the 2023-03 milestone since an experiment today with the published version of Cobra shows this issue is not yet fixed in (merged into) the main branch.
