### ISSUE TITLE
Add option to use different algorithms

### ISSUE THREAD

**Issue by MatthiasRoelsPython** [PythonPredictions/cobra#14]
In some of our projects, it is necessary to be able to have a library in which you can deviate from the ordinary regression models with a binary target. Our current methodology should work fine in those cases, so it is only natural to add those to COBRA. 

As the model now is encapsulated in a class and is heavily used in the `ForwardFeatureSelection` class, it makes sense to implement these models by means of an [(abstract) factory design pattern](https://medium.com/design-patterns-with-python/hihih-2ce4b45624d6) to make them easy to use.

**Comment by sborms** [comment]
For the new release we made a simple distinction between LogisticRegressionModel and LinearRegressionModel, used within ForwardFeatureSelection.

If we include more models it would indeed make sense to add a general ModelFactory type class on top. Nice design pattern!
