### ISSUE TITLE
Link to the docs/tutorial/... on library import (inital load)

### ISSUE THREAD

**Issue by patrickleonardy** [PythonPredictions/cobra#151]
# Task Title

Task: Include a logging to make it easy to find the tutorial  page

## Task Description

This issue will...

**Comment by sandervh14** [comment]
This was actually a VERY good idea.
I'd like to suggest though to use the opportunity to also to link to the documentation, the DFT presentation for details on inner workings and maybe also just the github URL for people that downloaded the library by instruction of someone else.

**Comment by ZlaTanskY** [comment]
Why do we add documentation in the code while this is already available in the readme on the github mainpage? (see also this [link](https://github.com/PythonPredictions/cobra#documentation-and-extra-material))

In my opinion we should separate the place where we put code and where we put documentation, this to avoid clutter whenever we rerun a notebook or a script.

**Comment by patrickleonardy** [comment]
It is true that this pops up each time a script is run but in the end it is just a little message under the imports cell. I would not mind as this can be minimized in a notebook . However, I am wondering if this can cause problems when using cobra in production. If this is the case, I suggest that we take it out and include it in `help(cobra)` or `?cobra`. Like this it only shows when the user wants to see it.

**Comment by patrickleonardy** [comment]
Sorry did close this issue on accident

**Comment by sandervh14** [comment]
Fine for me too!

**Comment by patrickleonardy** [comment]
okay I'll add it then in the `__init__.py` file like this it shows up by calling `help(cobra)`. To add the Powerpoint presentation I will convert it to a pdf and upload it to GitHub if this is fine for you.
