### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#26]
Make documentation more precise, based from feedback of our users, these are the points they were missing:

  * if X happens, do Y or that (example when variable is dropped when it has on 6 bins, but we set 10)
  * be more explicit in what Cobra does and does not do
    * AUC is being optimized
    * no interaction variables
    * if model fails, try this or that
    * ...
  * why it works
    * why logistic regression (and not decision tree)
    * why we bin continuous variables (we could keep them as they are)
    * why we do incidence replacement
    * link to papers/more fundamental research
  * how some steps works
    * show on example how regrouping works
  * add link to Geert's paper
  * explain how preprocessing works
    * regrouping
    * binning

**Comment by sborms** [comment]
For the new release, there will be more documentation across the README page, the code functions, and the tutorials. Not yet fully optimal but a good step forwards. Most of your points are better covered.
