### ISSUE TITLE
Improve PIGs

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#32]
After some discussion with Geert, below his suggestions:

**Incidence graph**: 

- the colors don't really match with our slide template AND I believe the frequency bars should be less visually attractive (eg grey), while the incidence graph should be really present (blue). 
- from this graph it is impossible to guess which Y-axis (left vs right) applies to incidence, and which applies to proportion of cases. Usually, I would align the color of the axis to the graph color - i.e. grey for population size on the left and blue for incidence on the right. 
- I would personally put incidence on the left instead of the right, as that is the most important information and typically, we are used to look at the left axis first. I would also clean up the graph labels a little so they don't contain .0 (left, right and bottom)...
- make sure we always refer to them as Predictor **Insights** Graphs!

Attached is how the plot could look like.

![PIG_age_v2](https://user-images.githubusercontent.com/20231499/110914611-e0dc8680-8316-11eb-800a-18cebbd52789.png)

**Comment by sandervh14** [comment]
Reopening this issue for 2 requested bugfixes:

- the y axis scale can be misleading when the variation on target values is small, for example:
   ![image](https://user-images.githubusercontent.com/4201920/129329734-b218d04e-7870-48ed-91fd-27b1cbf1bc08.png)
- long bin labels get shifted on the x-axis, for example:
   ![image](https://user-images.githubusercontent.com/4201920/129330183-f7b9aa97-0f46-4dfa-9d94-72ab42228df0.png)

**Comment by hendrikdewinter8** [comment]
Should we apply fixed Y axis for all PIG graphs within one analysis?

**Comment by sborms** [comment]
Fixing the Y-axis is too dangerous as there can be a large Y differential for some bins and small for others. I would (similar to what I saw Sander suggesting elsewhere) take the min-max proportional difference, and when it's small (<5%), we let the Y-axis go from [0.90\*min, 1.10\*max] (be careful with negative values).

I think that would suffice as a fix. It's never going to be visually perfect for all cases.

**Comment by sandervh14** [comment]
Implemented a fix for the two remaining problems discussed above. Results:
![image](https://user-images.githubusercontent.com/4201920/135506143-02d8e668-b6ef-4141-8b11-e4fa136a156d.png)
![image](https://user-images.githubusercontent.com/4201920/135506309-965136cc-fdbf-48c5-bad5-ba404369585b.png)
