### ISSUE TITLE
Variable importance is empty

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#34]
Sometime plot variable importance has empty fields - this occured on titanic dataset.
We need to reproduce and locate this error

**Comment by JanBenisek** [comment]
![image](https://user-images.githubusercontent.com/20231499/110914493-bdb1d700-8316-11eb-99c3-45ee221c1364.png)

**Comment by sborms** [comment]
@hendrikdewinter8 You have been working with the Titanic dataset. Have you noticed any of this behavior?

**Comment by hendrikdewinter8** [comment]
@sborms , no this did not occur for me.

**Comment by sborms** [comment]
Ok, I will close this then. Also didn't occur in my testing, nor in Sander's, and hard to reproduce with this info.
