### ISSUE TITLE
Provide functionality for scoring

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#44]
Provide for user functions which allow easy scoring of trained model. Currently, we export the data prep and model pipeline as dict, but in order to produce scores, users need to manually calculate them.

To be discussed how this will be implemented (perhaps as a predict_proba in the model class?)

- [x] Discuss implementation
- [x] Implement
- [x] update documentation

**Comment by JanBenisek** [comment]
This was implemented in previous release, only updated documentation is missing.

**Comment by sborms** [comment]
There is some (sparse) documentation now - the `score_model()` and `evaluate()` methods are quite explanatory anyhow.
