### ISSUE TITLE
Preprocessing - categorical_data_preprocessor

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#65]
- [x] We need to add option `model_type` which can be [`classification`, `regression`] to the class: https://github.com/PythonPredictions/cobra/blob/6ef6723440add755ec94b46ad87d1a913d027776/cobra/preprocessing/categorical_data_processor.py#L61
- [x] Think about implementation. I'd say keep this as it is, but add a paremeter `model_type`. https://github.com/PythonPredictions/cobra/blob/6ef6723440add755ec94b46ad87d1a913d027776/cobra/preprocessing/categorical_data_processor.py#L216
- [x] We need to add statistical test to regroup categories given continuous target. I'd choose non-parametric version of t-test [mann whitney](https://www.medcalc.org/manual/mannwhitney.php) or [kruskal walis](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test). But I am open to suggestions. There'd be two methods and `_compute_p_value`  would choose one or the other based on input parameter. https://github.com/PythonPredictions/cobra/blob/6ef6723440add755ec94b46ad87d1a913d027776/cobra/preprocessing/categorical_data_processor.py#L399
 - [x] Document and write/modify unit tests

**Comment by MatthiasRoels** [comment]
As an alternative, you can use a more pragmatic approach and do the regrouping based on group size (regroup below a threshold size). You should benchmark this first to see if you don't loose a lot of model performance (I guess that is not the case). This has the added value that the number of categories will typically smaller than is currently the case, which is good for interpretability too.

**Comment by JanBenisek** [comment]
Agree, but I think the priority is to add functionality for linear regression, without changing current behavior.
