### ISSUE TITLE
Preprocessing - preprocessor

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#66]
First implement changes in `target_encoder` and `categorical_data_processor` before starting this. 

- [x] Add parameter  `model_type` which can be [`classification`, `regression`] to the input. https://github.com/PythonPredictions/cobra/blob/6ef6723440add755ec94b46ad87d1a913d027776/cobra/preprocessing/preprocessor.py#L56
- [x] Make sure to change the `from_params`: https://github.com/PythonPredictions/cobra/blob/6ef6723440add755ec94b46ad87d1a913d027776/cobra/preprocessing/preprocessor.py#L68
- [x] Make sure that the `pipeline` has also this new parameter when saving (`pipeline["model_type"] = 'classification'`), loading and validating: https://github.com/PythonPredictions/cobra/blob/48d8a9aefbcbde7ecc898da69974a9b23727744c/cobra/preprocessing/preprocessor.py#L396 and https://github.com/PythonPredictions/cobra/blob/48d8a9aefbcbde7ecc898da69974a9b23727744c/cobra/preprocessing/preprocessor.py#L424
- [x]  Document and write/modify unit tests

**Comment by sandervh14** [comment]
Reopening to file a bugfix in the creation of the preprocessor with from_params().
