### ISSUE TITLE
Model_building - models

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#69]
- [x] Create the same model class as for logistic regression but for regression. Let's use model from sklearn, RMSE as evaluation, all the relevant model parameters: https://github.com/PythonPredictions/cobra/blob/48d8a9aefbcbde7ecc898da69974a9b23727744c/cobra/model_building/models.py#L11
- [x] Document and write/modify unit tests

**Comment by MatthiasRoels** [comment]
Alternatively, you can redesign the whole construction so that ForwardFeatureSelection accepts any model class (with predefined structure) so that you decouple both classes.

**Comment by JanBenisek** [comment]
Isn't that the case now? If there is `LinearRegressionModel` with the same look as `LogisticRegressionModel`, forward selection will work.

**Comment by sandervh14** [comment]
Reopened to solve a bug in model scoring.
I attempted reusing the old pull request, but it will make reviewing unnecessarily complicated + github mentions it wants to automatically close the issue because an other issue to the old pull request is closed already.
So, see the new linked pull request.
