### ISSUE TITLE
Model_building - forward_selection

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#70]
- [x] This should be model-independent, test it.
- [x] Document and write/modify unit tests

**Comment by sandervh14** [comment]
Reopening, evaluating forward selection on a regression problem learns us that at the moment, the best predictor is chosen as the one with the highest RMSE, instead of lowest RMSE.
Probably because forward selection used to use "higher is better" reasoning for classification, with AUC as metric.
