### ISSUE TITLE
Evaluation - pigs_tables

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#75]
- [x] Add parameter `model_type` which can be [`classification`, `regression`]
- [x] Based on the parameter, change names (we no longer talk about incidence rate)
- [x] Document and write/modify unit tests

**Comment by sandervh14** [comment]
Committing what I have modified so far. I can spend time tomorrow on the unit test for regression and for trying out the results on the regression MVP test case.
