### ISSUE TITLE
Evaluation - plotting_utils

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#76]
- [x] Change names and labels. Based on the input, the function should know when use "AUC" or "RMSE". https://github.com/PythonPredictions/cobra/blob/4da81c6f99cdd7b1f9d98e4c98735fc1d853fa61/cobra/evaluation/plotting_utils.py#L9
- [x] Change names and labels here. Based on the input, the function should know when use "AUC" or "RMSE". https://github.com/PythonPredictions/cobra/blob/4da81c6f99cdd7b1f9d98e4c98735fc1d853fa61/cobra/evaluation/plotting_utils.py#L77
- [x] Document and write/modify unit tests

**Comment by hendrikdewinter8** [comment]
When testing the performance curves plot, for the tutorial of linear regression, I had following bug:
<img width="560" alt="linear_performancecurves" src="https://user-images.githubusercontent.com/88764819/134006108-41bb8e3a-1c20-42bc-b806-1775767eeb51.png">

**Comment by sborms** [comment]
Hi @hendrikdewinter8, I tried to set a reasonable automatic range for the y-axis, but seems I was a bit too quick. Goal is to have a bit of extra graph space on top. Maybe `np.arange(0, max_metric+1)` is more than sufficient, even for very large values (but might be too big for small values...). Feel free to see what works and push a branch with a fix to the repo.

**Comment by hendrikdewinter8** [comment]
@sborms , I used your suggestion and now it works fine! I'll commit it

**Comment by sandervh14** [comment]
Reopening shortly to upload a fix for the y axis in the model performance plot for forward feature selection:
![image](https://user-images.githubusercontent.com/4201920/135239753-8201d3ad-465f-4584-988b-27adef42602b.png)
