### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by JanBenisek** [PythonPredictions/cobra#77]
- [x] Explain methodology for linear regression in our docs
- [x] Add jupyter notebook with examples of usage (https://stackoverflow.com/questions/38526888/embed-ipython-notebook-in-sphinx-document)

**Comment by sborms** [comment]
Hi @hendrikdewinter8, whenever you are ready, you can show us what the tutorial notebooks look like so we can provide some feedback. :-)

**Comment by sborms** [comment]
Tutorials are now living in a separate top-level folder "Tutorials". I made some modifications and it looks clean now. Currently still under general-fixes branch but will merge with develop soon.

Would be cool to add NBs to Sphinx documentation website... To check.

**Comment by hendrikdewinter8** [comment]
@sborms Well done, Sam!! Looks good.
