### ISSUE TITLE
Add toy datasets

### ISSUE THREAD

**Issue by sandervh14** [PythonPredictions/cobra#81]
# Add toy datasets

Task: Adding toy datasets for maintainers and developers working with Cobra.

## Task Description

I'm often reproducing an issue with a dataset that I already have at hand, just like I'm doing now for issue #67.
But it would be more convenient to be able to just pick a toy dataset folder available within Cobra, like is the case in other libraries, like sklearn.
We already started this idea in #27, but that issue is not entirely solved yet and that dataset was very large.
Let's add some simple datasets, like the titanic classification case.
Or from our [Cobra dataset folder on Google Drive](https://drive.google.com/open?id=1e1gM4BpI682vDNO3lgCRAgfLjyWip9nF).
To be verified which datasets can be copied, according to the license.

**Comment by hendrikdewinter8** [comment]
I added two seaborn datasets (miles per gallon, penguins) to the drive.

**Comment by sandervh14** [comment]
Hi Hendrik! 
Thanks for doing that!
I'll however reopen this issue, because I intended the datasets to be included in the Cobra framework itself, such that developers working with Cobra can do something like this:
```
from cobra.datasets import load_miles_per_gallon, load_penguins

df_mpg = load_miles_per_gallon()
df_penguins = load_penguins()
```
Similar to how sklearn provides such functionality, see https://scikit-learn.org/stable/datasets/toy_dataset.html and https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html#sklearn.datasets.load_boston.

**Comment by sborms** [comment]
It's a good idea but I wonder if it's necessary since users can play with datasets from sklearn or seaborn or else. 

I would only do it if we have a very nice dataset that we can share and works well in the tutorials, or is particularly useful for testing. I think Hendrik is building the tutorials now with seaborn datasets, so he can import them straight from seaborn.

**Comment by sandervh14** [comment]
OK, I'll drop this issue. I was thinking of at least a wrapper for sklearn toy dataset creation methods + in the future our own datasets, but it doesn't make much sense creating that wrapper, if the tutorial documents to users how to load toy datasets from other libraries.
I remember there is an unfinished issue where I created a large dataset to test Cobra on, I'll add that one later though, that one does make sense to add.
