### ISSUE TITLE
Rethink the threshold of RMSE for preselection of predictors

### ISSUE THREAD

**Issue by hendrikdewinter8** [PythonPredictions/cobra#98]
# RETHINK the treshold of RMSE for preselection of predictors

Task: Change the thresholds for preselection of features. It cannot be a fixed threshold for every dataset.

## Task Description

As the square root of a variance, RMSE can be interpreted as the standard deviation of the unexplained variance, and has the useful property of being in the same units as the response variable.  In general, lower values of RMSE indicate better fit and people use values below 0.5 to indicate the fit of a model is good.
HOWEVER, we cannot ignore that RMSE is dependent on the scaling of the target variable. Therefore, I suggest to scale the RMSE on the scale of the response, thus divide by mean of the response for example: RMSE/mean(y).

An alternative is to let the user decide upon a treshold for RMSE, as in which error in the specific case can be deemed reasonable.

**Comment by sandervh14** [comment]
> An alternative is to let the user decide upon a treshold for RMSE, as in which error in the specific case can be deemed reasonable.

*At least* in some places, this is the case:

```
df_rmse = univariate_selection.compute_univariate_preselection(
    #...
    model_type="regression",
    preselect_rmse_threshold = 1.0, # We know that the target is between 0 and 4, so an rmse below 1 is fine, see next cells.
    preselect_overtrain_threshold = 0.05)
```
To be verified if this is the case everywhere.
And/or indeed the scaling solution you propose.

**Comment by sborms** [comment]
I propose to keep this as-is, and leave the threshold decision up to the user. Re-scaling RMSE might lead to confusion about what RMSE is being reported.

This is an interesting discussion that highlights other options and what to take into consideration: https://www.marinedatascience.co/blog/2019/01/07/normalizing-the-rmse/. 

If in practice users struggle with the threshold, we can reopen this issue.
